pre-commit: fix mypy error on OL10
Now that I've switched to OL10 for my laptop & development, I got the
following error on my first attempt to commit:

yo/util.py:385: error: Library stubs not installed for "pkg_resources"  [import]
yo/util.py:385: note: Hint: "python3 -m pip install types-setuptools"
yo/util.py:385: note: (or run "mypy --install-types" to install all missing stub packages)
yo/util.py:385: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 10 source files)

This seems to be because OL10 comes with setuptools 69, where
pkg_resources is untyped. However, setuptools 71 made it typed, and so
types-setuptools dropped the stubs. By specifying only types-setuptools,
I got a recent version (>71) with no types for pkg_resources, alongside
the system setuptools v69, which also has no types for pkg_resources.
Specify setuptools as an additional dependency in the pre-commit config
so that we pull in a new version of setuptools with the types.

This avoids adding new "type: ignore" statements (which could cause
errors themselves if unused). Leaving behind types-setuptools makes this
maximally compatible with older Pythons too.

Also drop subc from this list, because we have bundled it for a while
now.

Signed-off-by: Stephen Brennan <stephen.s.brennan@oracle.com>