yo nmi: fix crash
Running "yo nmi INSTANCE" gives:

Traceback (most recent call last):
  File "/home/stepbren/.local/bin/yo", line 33, in <module>
    sys.exit(load_entry_point('yo', 'console_scripts', 'yo')())
  File "/home/stepbren/repos/yo/yo/main.py", line 3861, in main
    ns.func(ns)
  File "/home/stepbren/repos/yo/yo/main.py", line 757, in base_run
    self.run()
  File "/home/stepbren/repos/yo/yo/main.py", line 1186, in run
    self.run_for_all(to_run)
  File "/home/stepbren/repos/yo/yo/main.py", line 1163, in run_for_all
    self.post_for_instance(instance)
  File "/home/stepbren/repos/yo/yo/main.py", line 2642, in post_for_instance
    if self.args.wait and self.target_state and not self.args.dry_run:
AttributeError: 'Namespace' object has no attribute 'wait'

Since "yo nmi" has no target_state, the --wait argument is not added to
its argument parser. We shouldn't access it directly. Add a getattr()
and default it to False.

Signed-off-by: Stephen Brennan <stephen.s.brennan@oracle.com>